CURRENT_DIR=$PWD
PARENT_DIR="$(dirname "$PWD")"
TMP_DIR=$PARENT_DIR/tmp
BUILD_DIR=$TMP_DIR/gyro-release
SOURCE_DIR=$PWD
OUT_DIR=$PARENT_DIR/out-release
PREFIX_PATH=/home/dumo/opt/Qt/6.0.3/gcc_64

mkdir -p $TMP_DIR && mkdir -p $BUILD_DIR \
 && cd $BUILD_DIR \
 && cmake $SOURCE_DIR \
 -DCMAKE_BUILD_TYPE=Release \
 -DBOOST_ROOT=$OUT_DIR/include \
 -DBOOST_INCLUDEDIR=$OUT_DIR/include \
 -DBOOST_LIBRARYDIR=$OUT_DIR/lib/ \
 -DINSTALL_VENDORED_LIBUNBOUND=ON \
 -DBUILD_GUI_DEPS=ON \
 -DMANUAL_SUBMODULES=1 \
 -DBUILD_TESTS=OFF \
 -DCMAKE_INSTALL_PREFIX=$OUT_DIR \
 -DCMAKE_PREFIX_PATH=$PREFIX_PATH \
 && make -j3 && make install
