#include "wallet_zyre_rpc_proxy.h"

#define ON_METHOD(f_name) \
  zyre.on_r("gyro_" #f_name, zyre::fwrap_r(&rpc_proxy::on_##f_name, this));

#define ON_METHOD_IMPL(f_name, st_name) \
  void rpc_proxy::on_##f_name(const tools::wallet_rpc::COMMAND_RPC_##st_name::request& req, zyre::resp_t r) \
  { \
    tools::wallet_rpc::COMMAND_RPC_##st_name::response res; epee::json_rpc::error er; \
    rpc_.on_##f_name(req, res, er); r(res); \
  }

namespace zyre { namespace wallet {

  rpc_proxy::rpc_proxy(tools::wallet2 *w) : rpc_(w) {}

  void rpc_proxy::init(zyre::client& zyre)
  {
    ON_METHOD( getbalance                   )
    ON_METHOD( getaddress                   )
    ON_METHOD( getaddress_index             )
    ON_METHOD( create_address               )
    ON_METHOD( label_address                )
    ON_METHOD( get_accounts                 )
    ON_METHOD( create_account               )
    ON_METHOD( label_account                )
    ON_METHOD( get_account_tags             )
    ON_METHOD( tag_accounts                 )
    ON_METHOD( untag_accounts               )
    ON_METHOD( set_account_tag_description  )
    ON_METHOD( getheight                    )
    ON_METHOD( transfer                     )
    ON_METHOD( transfer_split               )
    ON_METHOD( sign_transfer                )
    ON_METHOD( describe_transfer            )
    ON_METHOD( submit_transfer              )
    ON_METHOD( sweep_dust                   )
    ON_METHOD( sweep_all                    )
    ON_METHOD( sweep_single                 )
    ON_METHOD( relay_tx                     )
    ON_METHOD( make_integrated_address      )
    ON_METHOD( split_integrated_address     )
    ON_METHOD( store                        )
    ON_METHOD( get_payments                 )
    ON_METHOD( get_bulk_payments            )
    ON_METHOD( incoming_transfers           )
    ON_METHOD( rescan_blockchain            )
    ON_METHOD( set_tx_notes                 )
    ON_METHOD( get_tx_notes                 )
    ON_METHOD( set_attribute                )
    ON_METHOD( get_attribute                )
    ON_METHOD( get_tx_key                   )
    ON_METHOD( check_tx_key                 )
    ON_METHOD( get_tx_proof                 )
    ON_METHOD( check_tx_proof               )
    ON_METHOD( get_spend_proof              )
    ON_METHOD( check_spend_proof            )
    ON_METHOD( get_reserve_proof            )
    ON_METHOD( check_reserve_proof          )
    ON_METHOD( get_transfers                )
    ON_METHOD( get_transfer_by_txid         )
    ON_METHOD( sign                         )
    ON_METHOD( verify                       )
    ON_METHOD( export_outputs               )
    ON_METHOD( import_outputs               )
    ON_METHOD( export_key_images            )
    ON_METHOD( import_key_images            )
    ON_METHOD( make_uri                     )
    ON_METHOD( parse_uri                    )
    ON_METHOD( get_address_book             )
    ON_METHOD( add_address_book             )
    ON_METHOD( edit_address_book            )
    ON_METHOD( delete_address_book          )
    ON_METHOD( refresh                      )
    ON_METHOD( rescan_spent                 )
    ON_METHOD( start_spinning               )
    ON_METHOD( stop_spinning                )
    ON_METHOD( get_languages                )
    ON_METHOD( change_wallet_password       )
    ON_METHOD( is_multisig                  )
    ON_METHOD( prepare_multisig             )
    ON_METHOD( make_multisig                )
    ON_METHOD( export_multisig              )
    ON_METHOD( import_multisig              )
    ON_METHOD( finalize_multisig            )
    ON_METHOD( exchange_multisig_keys       )
    ON_METHOD( sign_multisig                )
    ON_METHOD( submit_multisig              )
    ON_METHOD( validate_address             )
    ON_METHOD( set_daemon                   )
    ON_METHOD( set_log_level                )
    ON_METHOD( set_log_categories           )
    ON_METHOD( estimate_tx_size_and_weight  )
    ON_METHOD( get_version                  )
  }

  ON_METHOD_IMPL( getbalance                   , GET_BALANCE                      )
  ON_METHOD_IMPL( getaddress                   , GET_ADDRESS                      )
  ON_METHOD_IMPL( getaddress_index             , GET_ADDRESS_INDEX                )
  ON_METHOD_IMPL( create_address               , CREATE_ADDRESS                   )
  ON_METHOD_IMPL( label_address                , LABEL_ADDRESS                    )
  ON_METHOD_IMPL( get_accounts                 , GET_ACCOUNTS                     )
  ON_METHOD_IMPL( create_account               , CREATE_ACCOUNT                   )
  ON_METHOD_IMPL( label_account                , LABEL_ACCOUNT                    )
  ON_METHOD_IMPL( get_account_tags             , GET_ACCOUNT_TAGS                 )
  ON_METHOD_IMPL( tag_accounts                 , TAG_ACCOUNTS                     )
  ON_METHOD_IMPL( untag_accounts               , UNTAG_ACCOUNTS                   )
  ON_METHOD_IMPL( set_account_tag_description  , SET_ACCOUNT_TAG_DESCRIPTION      )
  ON_METHOD_IMPL( getheight                    , GET_HEIGHT                       )
  ON_METHOD_IMPL( transfer                     , TRANSFER                         )
  ON_METHOD_IMPL( transfer_split               , TRANSFER_SPLIT                   )
  ON_METHOD_IMPL( sign_transfer                , SIGN_TRANSFER                    )
  ON_METHOD_IMPL( describe_transfer            , DESCRIBE_TRANSFER                )
  ON_METHOD_IMPL( submit_transfer              , SUBMIT_TRANSFER                  )
  ON_METHOD_IMPL( sweep_dust                   , SWEEP_DUST                       )
  ON_METHOD_IMPL( sweep_all                    , SWEEP_ALL                        )
  ON_METHOD_IMPL( sweep_single                 , SWEEP_SINGLE                     )
  ON_METHOD_IMPL( relay_tx                     , RELAY_TX                         )
  ON_METHOD_IMPL( make_integrated_address      , MAKE_INTEGRATED_ADDRESS          )
  ON_METHOD_IMPL( split_integrated_address     , SPLIT_INTEGRATED_ADDRESS         )
  ON_METHOD_IMPL( store                        , STORE                            )
  ON_METHOD_IMPL( get_payments                 , GET_PAYMENTS                     )
  ON_METHOD_IMPL( get_bulk_payments            , GET_BULK_PAYMENTS                )
  ON_METHOD_IMPL( incoming_transfers           , INCOMING_TRANSFERS               )
  ON_METHOD_IMPL( rescan_blockchain            , RESCAN_BLOCKCHAIN                )
  ON_METHOD_IMPL( set_tx_notes                 , SET_TX_NOTES                     )
  ON_METHOD_IMPL( get_tx_notes                 , GET_TX_NOTES                     )
  ON_METHOD_IMPL( set_attribute                , SET_ATTRIBUTE                    )
  ON_METHOD_IMPL( get_attribute                , GET_ATTRIBUTE                    )
  ON_METHOD_IMPL( get_tx_key                   , GET_TX_KEY                       )
  ON_METHOD_IMPL( check_tx_key                 , CHECK_TX_KEY                     )
  ON_METHOD_IMPL( get_tx_proof                 , GET_TX_PROOF                     )
  ON_METHOD_IMPL( check_tx_proof               , CHECK_TX_PROOF                   )
  ON_METHOD_IMPL( get_spend_proof              , GET_SPEND_PROOF                  )
  ON_METHOD_IMPL( check_spend_proof            , CHECK_SPEND_PROOF                )
  ON_METHOD_IMPL( get_reserve_proof            , GET_RESERVE_PROOF                )
  ON_METHOD_IMPL( check_reserve_proof          , CHECK_RESERVE_PROOF              )
  ON_METHOD_IMPL( get_transfers                , GET_TRANSFERS                    )
  ON_METHOD_IMPL( get_transfer_by_txid         , GET_TRANSFER_BY_TXID             )
  ON_METHOD_IMPL( sign                         , SIGN                             )
  ON_METHOD_IMPL( verify                       , VERIFY                           )
  ON_METHOD_IMPL( export_outputs               , EXPORT_OUTPUTS                   )
  ON_METHOD_IMPL( import_outputs               , IMPORT_OUTPUTS                   )
  ON_METHOD_IMPL( export_key_images            , EXPORT_KEY_IMAGES                )
  ON_METHOD_IMPL( import_key_images            , IMPORT_KEY_IMAGES                )
  ON_METHOD_IMPL( make_uri                     , MAKE_URI                         )
  ON_METHOD_IMPL( parse_uri                    , PARSE_URI                        )
  ON_METHOD_IMPL( get_address_book             , GET_ADDRESS_BOOK_ENTRY           )
  ON_METHOD_IMPL( add_address_book             , ADD_ADDRESS_BOOK_ENTRY           )
  ON_METHOD_IMPL( edit_address_book            , EDIT_ADDRESS_BOOK_ENTRY          )
  ON_METHOD_IMPL( delete_address_book          , DELETE_ADDRESS_BOOK_ENTRY        )
  ON_METHOD_IMPL( refresh                      , REFRESH                          )
  ON_METHOD_IMPL( rescan_spent                 , RESCAN_SPENT                     )
  ON_METHOD_IMPL( start_spinning               , START_SPINNING                   )
  ON_METHOD_IMPL( stop_spinning                , STOP_SPINNING                    )
  ON_METHOD_IMPL( get_languages                , GET_LANGUAGES                    )
  ON_METHOD_IMPL( change_wallet_password       , CHANGE_WALLET_PASSWORD           )
  ON_METHOD_IMPL( is_multisig                  , IS_MULTISIG                      )
  ON_METHOD_IMPL( prepare_multisig             , PREPARE_MULTISIG                 )
  ON_METHOD_IMPL( make_multisig                , MAKE_MULTISIG                    )
  ON_METHOD_IMPL( export_multisig              , EXPORT_MULTISIG                  )
  ON_METHOD_IMPL( import_multisig              , IMPORT_MULTISIG                  )
  ON_METHOD_IMPL( finalize_multisig            , FINALIZE_MULTISIG                )
  ON_METHOD_IMPL( exchange_multisig_keys       , EXCHANGE_MULTISIG_KEYS           )
  ON_METHOD_IMPL( sign_multisig                , SIGN_MULTISIG                    )
  ON_METHOD_IMPL( submit_multisig              , SUBMIT_MULTISIG                  )
  ON_METHOD_IMPL( validate_address             , VALIDATE_ADDRESS                 )
  ON_METHOD_IMPL( set_daemon                   , SET_DAEMON                       )
  ON_METHOD_IMPL( set_log_level                , SET_LOG_LEVEL                    )
  ON_METHOD_IMPL( set_log_categories           , SET_LOG_CATEGORIES               )
  ON_METHOD_IMPL( estimate_tx_size_and_weight  , ESTIMATE_TX_SIZE_AND_WEIGHT      )
  ON_METHOD_IMPL( get_version                  , GET_VERSION                      )

} /* wallet */
} /* zyre */
